### ISSUE TITLE
Error in the Readme

### ISSUE THREAD

**Issue by AlexanderViken** [dalexsoto/AlexTouch.GoogleAdMobAds#1]
var ad = new GADBannerView(new RectangleF(new PointF(0,0), GADBannerView.GAD_SIZE_300x250))

should be
var ad = new GADBannerView(GADAdSizeCons.MediumRectangle,new PointF(0,0))

**Comment by dalexsoto** [comment]
Ups wrong thread

**Comment by dalexsoto** [comment]
Thanks, will update
