### ISSUE TITLE
Namespace

### ISSUE THREAD

**Issue by jonathanpeppers** [dalexsoto/AlexTouch.GoogleAdMobAds#3]
This is a great working copy of this binding, thanks for the good work.

Would you be willing to remove your name from the namespace?

It could probably be merged into here otherwise: https://github.com/mono/monotouch-bindings

**Comment by dalexsoto** [comment]
Hello, whats wrong with the name?? Just wondering :)

**Comment by dalexsoto** [comment]
I have no problem with removing it, but just wanted to know whats wrong with it :)

**Comment by jonathanpeppers** [comment]
It is generally against coding standards to put your name in a namespace/class name, etc.

I can't find anything against doing this in Mono's coding standards, but I don't think Xamarin would merge your binding in (even though it works great for Admob 6.2), without the namespace changes.

If it were just GoogleAdmobAds instead of AlexTouch.GoogleAdmobAds, they'd take it.

**Comment by dalexsoto** [comment]
Mmmm will leave it like this here, and will make a fork of MonoTouch-bindings and do as you wish so you can merge it, is that ok?? =)

**Comment by jonathanpeppers** [comment]
Yeah that would be great, I realize you might use this in a submodule in another project or something.

Thanks for making this work--I started trying to make the new GADAdSize struct work until I found your project here.  Was a new Obj-C library the only way to do it?  It looked like they were using plain C on some of the library.

**Comment by dalexsoto** [comment]
Well I was re Exporting every symbol like this

```
-Xlinker -alias -Xlinker _kGADAdSizeLeaderboard -Xlinker _MTAdSizeLeaderboard
```

And then getting the struct like this

```
public static GADAdSize Leaderboard 
{
    get 
    {
        IntPtr RTLD_MAIN_ONLY = Dlfcn.dlopen (null, 0);
        IntPtr ptr = Dlfcn.dlsym (RTLD_MAIN_ONLY, "MTGADAdSizeLeaderboard");
        object obj = Marshal.PtrToStructure(ptr, typeof(GADAdSize));

        return (GADAdSize)obj;
    }
}
```

It worked really nice on Debug Mode, but on release mode those symbols were being stripped by mtouch so using --nosymbolstrip was not a good option due to it increased the size of the final app

So the solution was to create an objc static lib to make it work

btw im just updating my other bindings so I can include them in the pull request, give me a couple of hours :)

So what do you think??

**Comment by dalexsoto** [comment]
I had to re export symbols due to native linker was exposing them as local symbols and dlsym was not returning a pointer to them

**Comment by jonathanpeppers** [comment]
Yeah, that might be the only way to make it work.

I'm not sure if there is a way to keep the linker from stripping non-C# stuff.  Might be worth posting a question on StackOverflow.

**Comment by dalexsoto** [comment]
Already asked Sebastien, and he said currently there is no way to do it (from end users side)

**Comment by dalexsoto** [comment]
Sorry Jonathan I was not able to do it yesterday, but for sure you will have them today

**Comment by jonathanpeppers** [comment]
No rush.

It would just help alot of people out, when you get to it.

For my project I just forked your repo and changed it.

**Comment by jonathanpeppers** [comment]
This is so old, it should be closed.

**Comment by dalexsoto** [comment]
@jonathanpeppers cleaning the queue? haha, seems I never updated this. Thanks for closing.
